name: Running magicpod-analyzer

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0-11 * * 1-5'
  
jobs:
  cron:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js LTS
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'
        cache: 'yarn'
    - name: Install application and dependencies
      run: yarn install --frozen-lockfile
    - name: Run magicpod-analyzer
      run: yarn run magicpod-analyzer get-batch-runs -c magicpod_analyzer.yaml
      env:
        MAGICPOD_TOKEN: ${{ secrets.MAGICPOD_TOKEN }}
